$activeBorderColor = rgb(f07828)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = rgb(3d5058)
}
group {
    col.border_active = $activeBorderColor
}
decoration {
    rounding = 5
}
