# Workbench palette. Light ANSI colors darkened for readability.
accent = "#f07828"
cursor = "#f07828"
foreground = "#2d3e44"
background = "#e8e0d8"
selection_foreground = "#2d3e44"
selection_background = "#c1c0bc"
color0 = "#2d3e44"
color1 = "#b23a34"
color2 = "#1b733c"
color3 = "#8d561b"
color4 = "#1e698d"
color5 = "#7950ac"
color6 = "#24697d"
color7 = "#5a6f76"
color8 = "#5a6f76"
color9 = "#b23a34"
color10 = "#1b733c"
color11 = "#8d561b"
color12 = "#1e698d"
color13 = "#7950ac"
color14 = "#24697d"
color15 = "#2d3e44"
