background = #e8e0d8
foreground = #2d3e44
cursor-color = #f07828
cursor-text = #1e2c31
selection-background = #c1c0bc
selection-foreground = #2d3e44
palette = 0=#2d3e44
palette = 1=#b23a34
palette = 2=#1b733c
palette = 3=#8d561b
palette = 4=#1e698d
palette = 5=#7950ac
palette = 6=#24697d
palette = 7=#5a6f76
palette = 8=#5a6f76
palette = 9=#b23a34
palette = 10=#1b733c
palette = 11=#8d561b
palette = 12=#1e698d
palette = 13=#7950ac
palette = 14=#24697d
palette = 15=#2d3e44
