add_newline = false
format = '$hostname$git_branch$python$conda$env_var$character'

[hostname]
ssh_only = false
format = '[$hostname](bold blue)'

[git_branch]
symbol = ''
format = ' [\($branch\)](bold purple)'

[python]
symbol = ''
format = ' [$virtualenv](bold yellow)'
detect_extensions = []
detect_files = []
detect_folders = []

[conda]
symbol = ''
format = ' [$environment](bold yellow)'
ignore_base = false

[env_var.MISE_ENV]
format = ' [$env_value](bold yellow)'

[character]
success_symbol = ' [❯](bold green) '
error_symbol = ' [❯](bold red) '
